#!/bin/sh


DISK_PERCENT=$(df -h | awk '$NF=="/"{printf "%s\n", $5}')
MEM_PERCENT=$(free -m | awk 'NR==2{printf "%.0f%%\n", $3*100/$2 }')
SWAP_PERCENT=$(free -m | awk 'NR==3{printf "%.0f%%\n", $3*100/$2 }')
IP_ADDRESS=$(hostname -i | awk '{printf "%s\n", $1}')
NUM_USERS=$(users | wc -w)
NUM_PROCESSES=$(ps -A --no-headers | wc -l)

CPU_PERCENT=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}')
CPU_PERCENT=${CPU_PERCENT%.*}
if [[ ${CPU_PERCENT} < 1 ]]
then
    CPU_PERCENT=0
fi

CPU_PERCENT="${CPU_PERCENT}%"

ROUTABLE="\e[31m✘\e[0m"
if fping -c1 -t300 www.facebook.com 2>/dev/null 1>/dev/null
then
  ROUTABLE="\e[32m✔\e[0m"
fi

INTERNAL_DNS="\e[31m✘\e[0m"
if fping -c1 -t300 192.168.1.2 2>/dev/null 1>/dev/null
then
  INTERNAL_DNS="\e[32m✔\e[0m"
fi


UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINUTES=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)


echo "     ___________________________________________________________"
echo "    |\t\t\t\t\t\t\t\t|"
echo "    |  Disk Usage--: ${DISK_PERCENT} \tCPU Usage---: ${CPU_PERCENT}\t\t|"
echo "    |  Memory Usage: ${MEM_PERCENT} \tSwap Usage--: ${SWAP_PERCENT}\t\t|"
echo "    |  Processes---: ${NUM_PROCESSES} \tIP Address--: ${IP_ADDRESS}\t|"
echo "    |  Users-------: ${NUM_USERS} \t\t\t\t\t\t|"
echo "    |  Routable----: ${ROUTABLE} \t\tInternal DNS: ${INTERNAL_DNS}\t\t\t|"
echo "    |\t\t\t\t\t\t\t\t|"
echo "    |  Uptime: ${UPTIME_DAYS} days, ${UPTIME_HOURS} hours, ${UPTIME_MINUTES} minutes\t\t\t|"
echo "    |___________________________________________________________|"
